services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - '3030:3030'
    expose:
      - '3030'
    environment:
      ADMIN_PASSWORD: ${FUSEKI_PASSWORD}

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    depends_on:
      - fuseki
      - redis
    volumes:
      - ./data/backend/logs:/app/backend/logs
      - ./data/backend/jwt:/app/backend/jwt
      - ./data/backend/uploads:/app/backend/uploads
    expose:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN_NAME}`)'
      - 'traefik.http.routers.backend.entrypoints=websecure'
      - 'traefik.http.routers.backend.tls.certresolver=myresolver'
    env_file:
      - ./backend/.env
      - ./backend/.env.production
      - path: ./backend/.env.production.local
        required: false

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    depends_on:
      - backend
    restart: always
    expose:
      - '5000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN_NAME}`)'
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls.certresolver=myresolver'
    env_file:
      - ./frontend/.env
      - ./frontend/.env.production
      - path: ./frontend/.env.production.local
        required: false

  redis:
    image: redis
    container_name: redis
    expose:
      - '6379'
    volumes:
      - ./data/redis:/data:z
    command: ['redis-server', '--appendonly', 'yes']

  arena:
    image: activitypods/arena
    container_name: arena
    restart: always
    volumes:
      - ./arena.json:/opt/arena/src/server/config/index.json
    depends_on:
      - redis
    expose:
      - '4567'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.arena.rule=(Host(`${BACKEND_DOMAIN_NAME}`) && Path(`/jobs`))'
      - 'traefik.http.routers.arena.entrypoints=websecure'
      - 'traefik.http.routers.arena.tls.certresolver=myresolver'
    environment:
      REDIS_HOST: 'redis'
