version: '3.5'
services:
  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - "3030:3030"
    expose:
      - "3030"
    environment:
      ADMIN_PASSWORD: "admin"

  fuseki_test:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki_test
    volumes:
      - ./data/fuseki_test:/fuseki
    ports:
      - "3040:3030"
    expose:
      - "3040"
    environment:
      ADMIN_PASSWORD: "admin"
